Insert into TASKER_ALERT_REQUEST (ALERT_ID,ALERT_GROUP,ALERT_NAME,ALERT_SCRIPT,IS_VALID,THRESHOLD_CONDITION,NOTIFY_THRESHOLD,WARNING_THRESHOLD,CRITICAL_THRESHOLD,ALERT_TYPE,ALERT_USER_HOST,APPLICATION_DB,PRIORITY,ATTR_VALUE1,ATTR_VALUE2) 
values ((select nvl(max(alert_id),0)+1 from TASKER_ALERT_REQUEST),'ABP','TRB PUB LOG Backlog ','select count(1) from trb1_pub_log','Y','GREATER_THAN',-1,1000,10000,'QUERY',null,'abpapp',1,null,null);

Insert into TASKER_ALERT_REQUEST (ALERT_ID,ALERT_GROUP,ALERT_NAME,ALERT_SCRIPT,IS_VALID,THRESHOLD_CONDITION,NOTIFY_THRESHOLD,WARNING_THRESHOLD,CRITICAL_THRESHOLD,ALERT_TYPE,ALERT_USER_HOST,APPLICATION_DB,PRIORITY,ATTR_VALUE1,ATTR_VALUE2) 
values ((select nvl(max(alert_id),0)+1 from TASKER_ALERT_REQUEST),'ABP','TRB Stuck Thread','select count(1) from trb1_thr_cntrl th, trb1_members m  where THREAD_STATUS<>''UP'' and m.member_id=th.member_id and m.MEMBER_ID!=3016','Y','GREATER_THAN',-1,0,0,'QUERY',null,'abpapp',1,null,null);
commit;
Insert into TASKER_ALERT_REQUEST (ALERT_ID,ALERT_GROUP,ALERT_NAME,ALERT_SCRIPT,IS_VALID,THRESHOLD_CONDITION,NOTIFY_THRESHOLD,WARNING_THRESHOLD,CRITICAL_THRESHOLD,ALERT_TYPE,ALERT_USER_HOST,APPLICATION_DB,PRIORITY,ATTR_VALUE1,ATTR_VALUE2) 
values ((select nvl(max(alert_id),0)+1 from TASKER_ALERT_REQUEST),'ABP','TRB SUB LOG Backlog CM','select count(1) from trb1_sub_log where sub_Appl_id in (3007,3013)','Y','GREATER_THAN',-1,1000,5000,'QUERY',null,'abpapp',1,null,null);

Insert into TASKER_ALERT_REQUEST (ALERT_ID,ALERT_GROUP,ALERT_NAME,ALERT_SCRIPT,IS_VALID,THRESHOLD_CONDITION,NOTIFY_THRESHOLD,WARNING_THRESHOLD,CRITICAL_THRESHOLD,ALERT_TYPE,ALERT_USER_HOST,APPLICATION_DB,PRIORITY,ATTR_VALUE1,ATTR_VALUE2) 
values ((select nvl(max(alert_id),0)+1 from TASKER_ALERT_REQUEST),'ABP','TRB SUB LOG Backlog AR','select count(1) from trb1_sub_log where sub_Appl_id=3000','Y','GREATER_THAN',-1,1000,5000,'QUERY',null,'abpapp',1,null,null);

Insert into TASKER_ALERT_REQUEST (ALERT_ID,ALERT_GROUP,ALERT_NAME,ALERT_SCRIPT,IS_VALID,THRESHOLD_CONDITION,NOTIFY_THRESHOLD,WARNING_THRESHOLD,CRITICAL_THRESHOLD,ALERT_TYPE,ALERT_USER_HOST,APPLICATION_DB,PRIORITY,ATTR_VALUE1,ATTR_VALUE2) 
values ((select nvl(max(alert_id),0)+1 from TASKER_ALERT_REQUEST),'ABP','TRB SUB LOG Backlog ADJ update handler incremental Guiding','select count(1) from trb1_sub_log where sub_Appl_id=3016','Y','GREATER_THAN',-1,1000,5000,'QUERY',null,'epcapp',1,null,null);

Insert into TASKER_ALERT_REQUEST (ALERT_ID,ALERT_GROUP,ALERT_NAME,ALERT_SCRIPT,IS_VALID,THRESHOLD_CONDITION,NOTIFY_THRESHOLD,WARNING_THRESHOLD,CRITICAL_THRESHOLD,ALERT_TYPE,ALERT_USER_HOST,APPLICATION_DB,PRIORITY,ATTR_VALUE1,ATTR_VALUE2) 
values ((select nvl(max(alert_id),0)+1 from TASKER_ALERT_REQUEST),'ABP','TRB SUB LOG Backlog ADJ update handler incremental Rater','select count(1) from trb1_sub_log where sub_Appl_id=3015','Y','GREATER_THAN',-1,1000,5000,'QUERY',null,'epcapp',1,null,null);

Insert into TASKER_ALERT_REQUEST (ALERT_ID,ALERT_GROUP,ALERT_NAME,ALERT_SCRIPT,IS_VALID,THRESHOLD_CONDITION,NOTIFY_THRESHOLD,WARNING_THRESHOLD,CRITICAL_THRESHOLD,ALERT_TYPE,ALERT_USER_HOST,APPLICATION_DB,PRIORITY,ATTR_VALUE1,ATTR_VALUE2) 
values ((select nvl(max(alert_id),0)+1 from TASKER_ALERT_REQUEST),'ABP','TRB SUB LOG Backlog CL','select count(1) from trb1_sub_log where sub_Appl_id in (3012,3009)','Y','GREATER_THAN',-1,1000,5000,'QUERY',null,'abpapp',1,null,null);

Insert into TASKER_ALERT_REQUEST (ALERT_ID,ALERT_GROUP,ALERT_NAME,ALERT_SCRIPT,IS_VALID,THRESHOLD_CONDITION,NOTIFY_THRESHOLD,WARNING_THRESHOLD,CRITICAL_THRESHOLD,ALERT_TYPE,ALERT_USER_HOST,APPLICATION_DB,PRIORITY,ATTR_VALUE1,ATTR_VALUE2) 
values ((select nvl(max(alert_id),0)+1 from TASKER_ALERT_REQUEST),'ABP','TRB SUB LOG Backlog CM2SDP','select count(1) from trb1_sub_log where sub_Appl_id=3121','Y','GREATER_THAN',-1,1000,5000,'QUERY',null,'abpapp',1,null,null);

Insert into TASKER_ALERT_REQUEST (ALERT_ID,ALERT_GROUP,ALERT_NAME,ALERT_SCRIPT,IS_VALID,THRESHOLD_CONDITION,NOTIFY_THRESHOLD,WARNING_THRESHOLD,CRITICAL_THRESHOLD,ALERT_TYPE,ALERT_USER_HOST,APPLICATION_DB,PRIORITY,ATTR_VALUE1,ATTR_VALUE2) 
values ((select nvl(max(alert_id),0)+1 from TASKER_ALERT_REQUEST),'ABP','TRB SUB LOG Backlog Invoicing','select count(1) from trb1_sub_log where sub_Appl_id in (3017,3049,3008,3009)','Y','GREATER_THAN',-1,1000,5000,'QUERY',null,'abpapp',1,null,null);

Insert into TASKER_ALERT_REQUEST (ALERT_ID,ALERT_GROUP,ALERT_NAME,ALERT_SCRIPT,IS_VALID,THRESHOLD_CONDITION,NOTIFY_THRESHOLD,WARNING_THRESHOLD,CRITICAL_THRESHOLD,ALERT_TYPE,ALERT_USER_HOST,APPLICATION_DB,PRIORITY,ATTR_VALUE1,ATTR_VALUE2) 
values ((select nvl(max(alert_id),0)+1 from TASKER_ALERT_REQUEST),'ABP','TRB SUB LOG Backlog CRM','select count(1) from trb1_sub_log where sub_Appl_id in (3014)','Y','GREATER_THAN',-1,1000,5000,'QUERY',null,'abpapp',1,null,null);
commit;


Insert into TASKER_ALERT_REQUEST (ALERT_ID,ALERT_GROUP,ALERT_NAME,ALERT_SCRIPT,IS_VALID,THRESHOLD_CONDITION,NOTIFY_THRESHOLD,WARNING_THRESHOLD,CRITICAL_THRESHOLD,ALERT_TYPE,ALERT_USER_HOST,APPLICATION_DB,PRIORITY,ATTR_VALUE1,ATTR_VALUE2) 
values ((select nvl(max(alert_id),0)+1 from TASKER_ALERT_REQUEST),'ABP','TRB Errors Backlog CM','select count(1) from trb1_sub_errs where sub_Appl_id in (3007,3013) and error_status not in (''COMPLETED'',''PURGED'')','Y','GREATER_THAN',-1,20,100,'QUERY',null,'abpapp',1,null,null);

Insert into TASKER_ALERT_REQUEST (ALERT_ID,ALERT_GROUP,ALERT_NAME,ALERT_SCRIPT,IS_VALID,THRESHOLD_CONDITION,NOTIFY_THRESHOLD,WARNING_THRESHOLD,CRITICAL_THRESHOLD,ALERT_TYPE,ALERT_USER_HOST,APPLICATION_DB,PRIORITY,ATTR_VALUE1,ATTR_VALUE2) 
values ((select nvl(max(alert_id),0)+1 from TASKER_ALERT_REQUEST),'ABP','TRB Errors Backlog AR','select count(1) from trb1_sub_errs where sub_Appl_id=3000 and error_status not in (''COMPLETED'',''PURGED'')','Y','GREATER_THAN',-1,20,100,'QUERY',null,'abpapp',1,null,null);

Insert into TASKER_ALERT_REQUEST (ALERT_ID,ALERT_GROUP,ALERT_NAME,ALERT_SCRIPT,IS_VALID,THRESHOLD_CONDITION,NOTIFY_THRESHOLD,WARNING_THRESHOLD,CRITICAL_THRESHOLD,ALERT_TYPE,ALERT_USER_HOST,APPLICATION_DB,PRIORITY,ATTR_VALUE1,ATTR_VALUE2) 
values ((select nvl(max(alert_id),0)+1 from TASKER_ALERT_REQUEST),'ABP','TRB Errors Backlog ADJ update handler incremental Guiding','select count(1) from trb1_sub_errs where sub_Appl_id=3016 and error_status not in (''COMPLETED'',''PURGED'')','Y','GREATER_THAN',-1,20,100,'QUERY',null,'epcapp',1,null,null);

Insert into TASKER_ALERT_REQUEST (ALERT_ID,ALERT_GROUP,ALERT_NAME,ALERT_SCRIPT,IS_VALID,THRESHOLD_CONDITION,NOTIFY_THRESHOLD,WARNING_THRESHOLD,CRITICAL_THRESHOLD,ALERT_TYPE,ALERT_USER_HOST,APPLICATION_DB,PRIORITY,ATTR_VALUE1,ATTR_VALUE2) 
values ((select nvl(max(alert_id),0)+1 from TASKER_ALERT_REQUEST),'ABP','TRB Errors Backlog ADJ update handler incremental Rater','select count(1) from trb1_sub_errs where sub_Appl_id=3015 and error_status not in (''COMPLETED'',''PURGED'')','Y','GREATER_THAN',-1,20,100,'QUERY',null,'epcapp',1,null,null);

Insert into TASKER_ALERT_REQUEST (ALERT_ID,ALERT_GROUP,ALERT_NAME,ALERT_SCRIPT,IS_VALID,THRESHOLD_CONDITION,NOTIFY_THRESHOLD,WARNING_THRESHOLD,CRITICAL_THRESHOLD,ALERT_TYPE,ALERT_USER_HOST,APPLICATION_DB,PRIORITY,ATTR_VALUE1,ATTR_VALUE2) 
values ((select nvl(max(alert_id),0)+1 from TASKER_ALERT_REQUEST),'ABP','TRB Errors Backlog CL','select count(1) from trb1_sub_errs where sub_Appl_id in (3012,3009) and error_status not in (''COMPLETED'',''PURGED'')','Y','GREATER_THAN',-1,20,100,'QUERY',null,'abpapp',1,null,null);

Insert into TASKER_ALERT_REQUEST (ALERT_ID,ALERT_GROUP,ALERT_NAME,ALERT_SCRIPT,IS_VALID,THRESHOLD_CONDITION,NOTIFY_THRESHOLD,WARNING_THRESHOLD,CRITICAL_THRESHOLD,ALERT_TYPE,ALERT_USER_HOST,APPLICATION_DB,PRIORITY,ATTR_VALUE1,ATTR_VALUE2) 
values ((select nvl(max(alert_id),0)+1 from TASKER_ALERT_REQUEST),'ABP','TRB Errors Backlog CM2SDP','select count(1) from trb1_sub_errs where sub_Appl_id=3121 and error_status not in (''COMPLETED'',''PURGED'')','Y','GREATER_THAN',-1,20,100,'QUERY',null,'abpapp',1,null,null);

Insert into TASKER_ALERT_REQUEST (ALERT_ID,ALERT_GROUP,ALERT_NAME,ALERT_SCRIPT,IS_VALID,THRESHOLD_CONDITION,NOTIFY_THRESHOLD,WARNING_THRESHOLD,CRITICAL_THRESHOLD,ALERT_TYPE,ALERT_USER_HOST,APPLICATION_DB,PRIORITY,ATTR_VALUE1,ATTR_VALUE2) 
values ((select nvl(max(alert_id),0)+1 from TASKER_ALERT_REQUEST),'ABP','TRB Errors Backlog Invoicing','select count(1) from trb1_sub_errs where sub_Appl_id in (3017,3049,3008,3009) and error_status not in (''COMPLETED'',''PURGED'')','Y','GREATER_THAN',-1,20,100,'QUERY',null,'abpapp',1,null,null);

Insert into TASKER_ALERT_REQUEST (ALERT_ID,ALERT_GROUP,ALERT_NAME,ALERT_SCRIPT,IS_VALID,THRESHOLD_CONDITION,NOTIFY_THRESHOLD,WARNING_THRESHOLD,CRITICAL_THRESHOLD,ALERT_TYPE,ALERT_USER_HOST,APPLICATION_DB,PRIORITY,ATTR_VALUE1,ATTR_VALUE2) 
values ((select nvl(max(alert_id),0)+1 from TASKER_ALERT_REQUEST),'ABP','TRB Errors Backlog CRM','select count(1) from trb1_sub_errs where sub_Appl_id in (3014) and error_status not in (''COMPLETED'',''PURGED'')','Y','GREATER_THAN',-1,20,100,'QUERY',null,'abpapp',1,null,null);
commit;


Insert into TASKER_ALERT_REQUEST (ALERT_ID,ALERT_GROUP,ALERT_NAME,ALERT_SCRIPT,IS_VALID,THRESHOLD_CONDITION,NOTIFY_THRESHOLD,WARNING_THRESHOLD,CRITICAL_THRESHOLD,ALERT_TYPE,ALERT_USER_HOST,APPLICATION_DB,PRIORITY,ATTR_VALUE1,ATTR_VALUE2) 
values ((select nvl(max(alert_id),0)+1 from TASKER_ALERT_REQUEST),'ABP','AC1_Control Insert to Collection files backlog','select  count(1) FILES_COUNT from  ac1_control where NXT_PGM_NAME in (''CL_EV'',''CL_GK'',''CL_EX'') and CUR_FILE_ALIAS=''CL_DATA_FA'' and SYS_CREATION_DATE >sysdate-5','Y','GREATER_THAN',-1,1,500,'QUERY',null,'abpapp',1,null,null);

Insert into TASKER_ALERT_REQUEST (ALERT_ID,ALERT_GROUP,ALERT_NAME,ALERT_SCRIPT,IS_VALID,THRESHOLD_CONDITION,NOTIFY_THRESHOLD,WARNING_THRESHOLD,CRITICAL_THRESHOLD,ALERT_TYPE,ALERT_USER_HOST,APPLICATION_DB,PRIORITY,ATTR_VALUE1,ATTR_VALUE2) 
values ((select nvl(max(alert_id),0)+1 from TASKER_ALERT_REQUEST),'ABP','Talking Tech files today','select count(1) from AR3_GWLS_FILE_STATUS where FILE_PROCESS like ''AR9SFTPTLK'' and SYS_CREATION_DATE>sysdate-1','Y','LESS_THAN',-1,2,0,'QUERY',null,'abpapp',1,null,null);


Insert into TASKER_ALERT_REQUEST (ALERT_ID,ALERT_GROUP,ALERT_NAME,ALERT_SCRIPT,IS_VALID,THRESHOLD_CONDITION,NOTIFY_THRESHOLD,WARNING_THRESHOLD,CRITICAL_THRESHOLD,ALERT_TYPE,ALERT_USER_HOST,APPLICATION_DB,PRIORITY,ATTR_VALUE1,ATTR_VALUE2) 
values ((select nvl(max(alert_id),0)+1 from TASKER_ALERT_REQUEST),'ABP','CCS Failed to send collection letters','select count(1)  from  ccs1_request ccs, ccs1_req_type req_type , cl1_coll_entity cl where  cl.entity_id=ccs.ENTITY_ID and req_type.request_type_id = ccs.request_type_id and CODE in (''IFLBCOL01'', ''IFLBCOL07'', ''IFLBCOL31'', ''IFLBCOL36'',''IFLBFIN04'') and trunc(ccs.ISSUE_DATE) = trunc(sysdate-1 ) and ccs.STATUS_CODE=''REJECTED''','Y','GREATER_THAN',-1,0,50,'QUERY',null,'abpapp',1,null,null);
commit;


Insert into TASKER_ALERT_REQUEST (ALERT_ID,ALERT_GROUP,ALERT_NAME,ALERT_SCRIPT,IS_VALID,THRESHOLD_CONDITION,NOTIFY_THRESHOLD,WARNING_THRESHOLD,CRITICAL_THRESHOLD,ALERT_TYPE,ALERT_USER_HOST,APPLICATION_DB,PRIORITY,ATTR_VALUE1,ATTR_VALUE2) 
values ((select nvl(max(alert_id),0)+1 from TASKER_ALERT_REQUEST),'ABP','Pending AR Gateway Listner file','select count(1) from ar3_gwls_file_status where FILE_PROCESS_STATE in (''AF'',''IU'') and SYS_CREATION_DATE>=to_date(''01-JUN-2021'',''DD-MON-YYYY'') and FILE_PROCESS<>''AR9SFTP754''','Y','GREATER_THAN',-1,0,5,'QUERY',null,'abpapp',1,null,null);


Insert into TASKER_ALERT_REQUEST (ALERT_ID,ALERT_GROUP,ALERT_NAME,ALERT_SCRIPT,IS_VALID,THRESHOLD_CONDITION,NOTIFY_THRESHOLD,WARNING_THRESHOLD,CRITICAL_THRESHOLD,ALERT_TYPE,ALERT_USER_HOST,APPLICATION_DB,PRIORITY,ATTR_VALUE1,ATTR_VALUE2) 
values ((select nvl(max(alert_id),0)+1 from TASKER_ALERT_REQUEST),'ABP','AC Manager Failed to move files-FR','SELECT count(1) FROM AC1_CONTROL AC, AC1_SITES_ROUTING ASR, AC1_FILE_SYSTEM_DEF AFSD WHERE AC.file_status NOT IN (''AF'', ''HO'', ''WA'') AND AC.FILE_CREATE_DATE > SYSDATE -7 AND AC.DEST_ROUT_CRTRIA=ASR.ROUTING_CRITERIA AND ASR.LOGICAL_FS=AFSD.LOGICAL_FS AND AFSD.HOST_NAME<>AC.HOST_NAME and file_create_date<sysdate-0.003','Y','GREATER_THAN',-1,0,15,'QUERY',null,'abpapp',1,null,null);

Insert into TASKER_ALERT_REQUEST (ALERT_ID,ALERT_GROUP,ALERT_NAME,ALERT_SCRIPT,IS_VALID,THRESHOLD_CONDITION,NOTIFY_THRESHOLD,WARNING_THRESHOLD,CRITICAL_THRESHOLD,ALERT_TYPE,ALERT_USER_HOST,APPLICATION_DB,PRIORITY,ATTR_VALUE1,ATTR_VALUE2) 
values ((select nvl(max(alert_id),0)+1 from TASKER_ALERT_REQUEST),'ABP','AC Manager Failed to move files-FR','SELECT count(1) FROM AC1_CONTROL AC, AC1_SITES_ROUTING ASR, AC1_FILE_SYSTEM_DEF AFSD WHERE AC.file_status NOT IN (''AF'', ''HO'', ''WA'') AND AC.FILE_CREATE_DATE > SYSDATE -7 AND AC.DEST_ROUT_CRTRIA=ASR.ROUTING_CRITERIA AND ASR.LOGICAL_FS=AFSD.LOGICAL_FS AND AFSD.HOST_NAME<>AC.HOST_NAME and file_create_date<sysdate-0.003','Y','GREATER_THAN',-1,0,15,'QUERY',null,'epcapp',1,null,null);
commit;



Insert into TASKER_ALERT_REQUEST (ALERT_ID,ALERT_GROUP,ALERT_NAME,ALERT_SCRIPT,IS_VALID,THRESHOLD_CONDITION,NOTIFY_THRESHOLD,WARNING_THRESHOLD,CRITICAL_THRESHOLD,ALERT_TYPE,ALERT_USER_HOST,APPLICATION_DB,PRIORITY,ATTR_VALUE1,ATTR_VALUE2) 
values ((select nvl(max(alert_id),0)+1 from TASKER_ALERT_REQUEST),'ABP','AC Manager Failed AR files','select  count(1) from ac1_control where FILE_STATUS in (''AF'') and SYSTEM_ID not in (''BL'',''TC'') and NXT_PGM_NAME not in (''CL_EV'',''CL_EX'') and SYS_CREATION_DATE>sysdate-20','Y','GREATER_THAN',-1,0,5,'QUERY',null,'epcapp',1,null,null);

commit;