
 CREATE TABLE TASKER_REQUEST
   (	"NAME" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"REQUESTOR" VARCHAR2(200 BYTE), 
	"ENABLED" VARCHAR2(2 BYTE), 
	"FREQUENCY" VARCHAR2(200 BYTE), 
	"TIME" VARCHAR2(4000 BYTE), 
	"PATH" VARCHAR2(4000 BYTE), 
	"FILENAME" VARCHAR2(4000 BYTE), 
	"EMAIL_SUBJECT" VARCHAR2(4000 BYTE), 
	"EMAIL_IF_PRE_COND_IS_TRUE" CHAR(1 BYTE), 
	"EMAIL_LIST" VARCHAR2(4000 BYTE), 
	"EMAIL_HEAD" VARCHAR2(4000 BYTE), 
	"LASTEXECUTED" DATE);

grant all on tasker_Request to public ;
